### ISSUE TITLE
Wind technology

### ISSUE THREAD

**Issue by Alematiale** [pielube/MESSpy#33]
Review code. 
Fix negative energy balances issue (pp.total_balances(study_case,'p2','electricity'))

**Comment by Alematiale** [comment]
Consider the option of including windpowerlib features (https://windpowerlib.readthedocs.io/en/stable/).
Replicate the same approach used with pvlib.

**Comment by AndreAdemollo** [comment]
Same approach used with pvlib has been implemented. Issue resolved in commit dated October 1st
