### ISSUE TITLE
Ageing effects for hydrogen components: enhancing tracking capabilities for multiple modules configurations in electrolyzer.py and fuel_cell.py

### ISSUE THREAD

**Issue by Alematiale** [pielube/MESSpy#65]
Implement a structure to keep track of the degradation history of the different modules for both components, electrolyzer.py and fuel_cell.py. A dictionary structure is already in place for a single module (up to 1 MW). 
I suggest transitioning from a single dictionary to a nested format. This will allow for the tracking of each module, enhancing data analysis and detailed performance assessment. Useful when working with industrial-scale stacks (tens of MW).

**Tasks:**

1. Improve dictionary structure in both components.
2. Update documentation.
3. Validation.

**Outcomes:**

1. Detailed degradation tracking for every module.
2. Improved model reliability and maintenance planning.

**Comment by AndreAdemollo** [comment]
Issue resolved on commit dated October 1st
